from __future__ import annotations

import argparse
import json
import re
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path


@dataclass
class Section:
    title: str
    body: str
    order: int


BUCKET_RULES: list[tuple[str, str, list[str]]] = [
    (
        "programs",
        "PROGRAMS",
        [
            "program", "programs", "undergraduate", "graduate", "postgraduate",
            "phd", "ms", "masters", "mphil", "department-wise", "degree",
            "faculty and programs",
        ],
    ),
    (
        "fees",
        "FEES AND FINANCE",
        [
            "fee", "fees", "financial", "finance", "tuition", "challan",
            "refund", "hostel fee", "admission fee",
        ],
    ),
    (
        "admissions",
        "ADMISSIONS, ELIGIBILITY, MERIT, TESTS",
        [
            "admission", "admissions", "eligibility", "merit", "aggregate",
            "entry test", "nat", "hat", "ecat", "deadline", "requirements",
            "faq", "prospectus",
        ],
    ),
    (
        "scholarships",
        "SCHOLARSHIPS AND AID",
        [
            "scholarship", "scholarships", "financial aid", "peef", "need-based",
            "honhaar", "sponsor",
        ],
    ),
    (
        "campus",
        "CAMPUS, FACILITIES, STUDENT LIFE",
        [
            "hostel", "campus", "transport", "sports", "wifi", "student life",
            "timings", "office timings", "library",
        ],
    ),
    (
        "contacts",
        "CONTACTS, ADMIN, SUPPORT CELLS",
        [
            "contact", "contacts", "phone", "email", "vice chancellor", "hod",
            "director", "cell", "ncfa", "ncgsa", "harassment", "support",
        ],
    ),
    (
        "research",
        "RESEARCH, NEWS, EVENTS",
        [
            "research", "lab", "labs", "centre", "center", "quality enhancement",
            "news", "events",
        ],
    ),
    (
        "reference",
        "REFERENCE / WEB CRAWL DUMPS",
        [
            "website full content", "detailed knowledge base", "full content",
            "why ist", "source", "raw",
        ],
    ),
]

BUCKET_ORDER = [
    "programs",
    "fees",
    "admissions",
    "scholarships",
    "campus",
    "contacts",
    "research",
    "reference",
    "other",
]


def read_text_file(path: Path) -> str:
    raw = path.read_bytes()
    for encoding in ("utf-8", "utf-8-sig", "cp1252", "latin-1"):
        try:
            text = raw.decode(encoding)
            if "\ufffd" not in text:
                return text
        except UnicodeDecodeError:
            continue
    return raw.decode("utf-8", errors="replace")


def parse_sections(text: str) -> tuple[str, list[Section]]:
    lines = text.splitlines()
    heading_indices: list[int] = []

    for idx, line in enumerate(lines):
        if line.startswith("## "):
            heading_indices.append(idx)

    if not heading_indices:
        return text, []

    preamble = "\n".join(lines[: heading_indices[0]]).rstrip("\n")
    sections: list[Section] = []

    for order, start in enumerate(heading_indices):
        end = heading_indices[order + 1] if order + 1 < len(heading_indices) else len(lines)
        title = lines[start][3:].strip()
        body = "\n".join(lines[start + 1 : end]).strip("\n")
        sections.append(Section(title=title, body=body, order=order))

    return preamble, sections


def score_bucket(text_l: str, keywords: list[str]) -> int:
    score = 0
    for kw in keywords:
        if kw in text_l:
            score += 1
    return score


def classify_section(section: Section) -> tuple[str, dict[str, int]]:
    title_l = section.title.lower()
    body_window = section.body[:2000].lower()
    combined = f"{title_l}\n{body_window}"

    bucket_scores: dict[str, int] = {}
    for bucket_id, _, keywords in BUCKET_RULES:
        s_title = score_bucket(title_l, keywords) * 3
        s_body = score_bucket(combined, keywords)
        bucket_scores[bucket_id] = s_title + s_body

    best_bucket = max(bucket_scores, key=bucket_scores.get)
    best_score = bucket_scores[best_bucket]
    if best_score <= 0:
        return "other", bucket_scores

    return best_bucket, bucket_scores


def render_grouped_output(
    source_name: str,
    preamble: str,
    grouped: dict[str, list[Section]],
) -> str:
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")
    out: list[str] = []

    out.append("=" * 70)
    out.append("AUTO-RESTRUCTURED KNOWLEDGE BASE")
    out.append("=" * 70)
    out.append("This file is generated by scripts/restructure_kb.py")
    out.append(f"Source: {source_name}")
    out.append(f"Generated (UTC): {ts}")
    out.append("")
    out.append("Classification method: heading/section keyword scoring and stable grouping.")
    out.append("No section content is dropped. Section bodies are copied as-is.")
    out.append("")

    if preamble.strip():
        out.append("-" * 70)
        out.append("ORIGINAL PREAMBLE")
        out.append("-" * 70)
        out.append(preamble)
        out.append("")

    for bucket_id in BUCKET_ORDER:
        sections = grouped.get(bucket_id, [])
        if not sections:
            continue

        label = "OTHER"
        for rid, rlabel, _ in BUCKET_RULES:
            if rid == bucket_id:
                label = rlabel
                break

        out.append("=" * 70)
        out.append(f"BUCKET: {label}")
        out.append("=" * 70)
        out.append("")

        for sec in sections:
            out.append(f"## {sec.title}")
            if sec.body:
                out.append(sec.body)
            out.append("")

    return "\n".join(out).rstrip() + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="Auto-restructure KB sections by heading-level classification.")
    parser.add_argument("--input", required=True, help="Input KB .txt path")
    parser.add_argument("--output", required=True, help="Output restructured .txt path")
    parser.add_argument(
        "--report",
        default="",
        help="Optional JSON report path with per-section bucket decision details",
    )
    args = parser.parse_args()

    in_path = Path(args.input)
    out_path = Path(args.output)

    if not in_path.exists():
        raise FileNotFoundError(f"Input file not found: {in_path}")

    source_text = read_text_file(in_path)
    preamble, sections = parse_sections(source_text)

    if not sections:
        out_path.write_text(source_text, encoding="utf-8")
        return

    grouped: dict[str, list[Section]] = {k: [] for k in BUCKET_ORDER}
    decisions: list[dict[str, object]] = []

    for sec in sections:
        bucket, scores = classify_section(sec)
        grouped.setdefault(bucket, []).append(sec)
        decisions.append(
            {
                "order": sec.order,
                "title": sec.title,
                "bucket": bucket,
                "scores": scores,
            }
        )

    output_text = render_grouped_output(str(in_path), preamble, grouped)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(output_text, encoding="utf-8")

    if args.report:
        report_path = Path(args.report)
        report_path.parent.mkdir(parents=True, exist_ok=True)
        report_path.write_text(
            json.dumps(
                {
                    "input": str(in_path),
                    "output": str(out_path),
                    "section_count": len(sections),
                    "buckets": {k: len(v) for k, v in grouped.items() if v},
                    "decisions": decisions,
                },
                indent=2,
                ensure_ascii=True,
            ),
            encoding="utf-8",
        )


if __name__ == "__main__":
    main()
